export const MemeUrls = [
  '/idle_game/memes/zipline.jpg',
  '/idle_game/memes/cat.webp',
  '/idle_game/memes/pickle.png',
  '/idle_game/memes/dog.webp',
  '/idle_game/memes/cinema.jpg',
  '/idle_game/memes/mike.jpg',
  '/idle_game/memes/angrycat.jpg',
  '/idle_game/memes/brian.webp',
  '/idle_game/memes/doge.jpg',
  '/idle_game/memes/ericandre.jpg',
  '/idle_game/memes/girlfriend.jpg',
  '/idle_game/memes/karlhavoc.jpg',
  '/idle_game/memes/leogatbsy.webp',
  '/idle_game/memes/leopoint.jpg',
  '/idle_game/memes/nyancat.png',
  '/idle_game/memes/pikachu.png',
  '/idle_game/memes/questionmark.png',
  '/idle_game/memes/rage.png',
  '/idle_game/memes/sponge1.webp',
  '/idle_game/memes/sponge2.jpg',
  '/idle_game/memes/steveharvey.jpg',
  '/idle_game/memes/successkid.webp',
  '/idle_game/memes/timhotdog.jpg',
  '/idle_game/memes/troll1.jpg',
  '/idle_game/memes/troll2.jpg',
  '/idle_game/memes/troll3.webp',
  '/idle_game/memes/troll4.jpg',
  '/idle_game/memes/trollface.jpg',
  '/idle_game/memes/walterwhite.jpg',
]

export type BlogPost = {
  title: string
  type: string
  duration: string
}

export const BlogPosts: BlogPost[] = [
  { title: 'Brian: Bad Luck or Just Desserts?', type: 'case study', duration: '90 min' },
  {
    title: 'Overly Attached Girlfriend Elopes at 35',
    type: 'where are they now',
    duration: '30 sec',
  },
  {
    title: 'This Pepe Collector just found his Golden Goose',
    type: 'breaking news',
    duration: '5 min',
  },
  {
    title: 'Imagine Dragons contracts Ligma while perfoming concert to Sugondese crowd',
    type: 'breaking news',
    duration: '5 sec',
  },
  {
    title: `Pickle Rick: The Nuance behind the Genius `,
    type: 'case study',
    duration: '1200 min',
  },
]

export const AdContent = [
  "Congraluations! You've won our sweepstakes!",
  'Tired of Ads? Try our Ad Block Service!',
  'Subscribe to SpywareVPN and get the first 48 months free!',
  'Warning! Virus detected! Download our Virus to clean your computer!',
  'ANNOYING POP-UP ANNOYING POP-UP ANNOYING POP-UP',
  'Special offer just for you and definitely not for anyone else!',
  'Become an overnight instagram influencer with this 10-week course',
  'You are the 100,000,000th person to breathe air today. Collect your reward',
]

export const brands = [
  // Tech & Software
  'google.com',
  'apple.com',
  'microsoft.com',
  'amazon.com',
  'facebook.com',
  'instagram.com',
  'twitter.com',
  'tiktok.com',
  'snapchat.com',
  'netflix.com',
  'spotify.com',
  'discord.com',
  'reddit.com',
  'linkedin.com',
  'zoom.us',
  'slack.com',
  'dropbox.com',
  'adobe.com',
  'salesforce.com',
  'nvidia.com',
  'intel.com',
  'amd.com',
  'dell.com',
  'hp.com',
  'lenovo.com',
  'samsung.com',
  'sony.com',
  'huawei.com',
  'xiaomi.com',
  'tesla.com',

  // Retail & E-Commerce
  'walmart.com',
  'target.com',
  'costco.com',
  'ikea.com',
  'homedepot.com',
  'lowes.com',
  'bestbuy.com',
  'alibaba.com',
  'aliexpress.com',
  'ebay.com',
  'etsy.com',
  'shopify.com',
  'zara.com',
  'uniqlo.com',
  'hm.com',
  'shein.com',
  'nike.com',
  'adidas.com',
  'puma.com',
  'underarmour.com',
  'newbalance.com',
  'patagonia.com',
  'northface.com',

  // Food & Beverage
  'mcdonalds.com',
  'burgerking.com',
  'wendys.com',
  'kfc.com',
  'subway.com',
  'dominos.com',
  'pizzahut.com',
  'starbucks.com',
  'dunkindonuts.com',
  'timhortons.com',
  'coca-cola.com',
  'pepsi.com',
  'drpepper.com',
  'redbull.com',
  'monsterenergy.com',
  'heineken.com',
  'budweiser.com',
  'nestle.com',
  'kelloggs.com',
  'pringles.com',
  'oreo.com',
  'lays.com',
  'doritos.com',
  'chipotle.com',
  'panerabread.com',
  'fiveguys.com',

  // Automotive
  'bmw.com',
  'mercedes-benz.com',
  'audi.com',
  'porsche.com',
  'ferrari.com',
  'lamborghini.com',
  'toyota.com',
  'honda.com',
  'ford.com',
  'chevrolet.com',
  'nissan.com',
  'volkswagen.com',
  'volvo.com',
  'hyundai.com',
  'kia.com',
  'mazda.com',
  'subaru.com',
]
