import Link from "@/node_modules/next/link"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const Header = () => {
  return (
    <header className="flex gap-3 items-end">
      <Link href={"/"}>
        <h2 className="text-xl font-medium text-purple-600 ">
          Connor's Portfolio
        </h2>
      </Link>
      <Link href={"/"}>
        <h2 className="">Home</h2>
      </Link>
      <Link href={"/blog"}>
        <h2 className="">Blog</h2>
      </Link>
    </header>
  )
}

const Footer = () => {
  return <footer>Thanks for Visiting</footer>
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`my-8 w-[50vw] mx-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
