export { audioEngine } from './engine'
export { SOUND_REGISTRY } from './registry'
export type { SoundKey, SfxKey, MusicKey } from './registry'
export { playSfx, preloadAll } from './sfx'
export type { SfxHandle, PlaySfxOptions } from './sfx'
export { getMusicChannel, stopAllMusic } from './music'
export type { MusicChannel, MusicPlayOptions } from './music'
export { useSfx, useMusic, useMusicEnded, unlockAudio } from './useAudio'
export type { UseMusicOptions, UseMusicResult } from './useAudio'
